### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by snop3252** [ethkat/tibia-ts3-teamspeakbot#22]
yarn ts3-setup
yarn run v1.17.3
$ babel-node -r node_modules/dotenv/config ./src/scripts/setup
⠋ Connecting to the DB/home/snop3252/tibia-ts3-teamspeakbot/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/snop3252/tibia-ts3-teamspeakbot/node_modules/.cache'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/home/snop3252/tibia-ts3-teamspeakbot/node_modules/mkdirp/index.js:71:13)
    at sync (/home/snop3252/tibia-ts3-teamspeakbot/node_modules/mkdirp/index.js:77:24)
    at sync (/home/snop3252/tibia-ts3-teamspeakbot/node_modules/mkdirp/index.js:77:24)
    at save (/home/snop3252/tibia-ts3-teamspeakbot/node_modules/@babel/register/lib/cache.js:50:20)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at Object.<anonymous> (/home/snop3252/tibia-ts3-teamspeakbot/node_modules/@babel/node/lib/_babel-node.js:234:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Ethaan** [comment]
in which OS are you?

**Comment by snop3252** [comment]
ubuntu-1604-xenial-

**Comment by Ethaan** [comment]
try with `sudo yarn ts3-setup` or be sure you have privileges on the current user

**Comment by snop3252** [comment]
I already had sudo, but it didn't work either.

**Comment by eduardokum** [comment]
Run yarn install before run ts3-setup

**Comment by Ethaan** [comment]
@snop3252 did @eduardokum suggestion fix the issue?

**Comment by snop3252** [comment]
@eduardokum yes it was done which operating system are you using?
@Ethaan it didn't work and I didn't test anymore

**Comment by eduardokum** [comment]
try do `sudo chmod 777 /home/snop3252/tibia-ts3-teamspeakbot/node_modules/ -Rf`

**Comment by Ethaan** [comment]
This is a duplicate, lets continue conversation on https://github.com/ethkat/tibia-ts3-teamspeakbot/issues/30
