### ISSUE TITLE
Errors when trying to set up the bot

### ISSUE THREAD

**Issue by Bielzinero** [ethkat/tibia-ts3-teamspeakbot#26]
I'm trying to set up the bot and I'm getting the following messages (after npm install)

```
Error: Cannot find module 'node_modules/dotenv/config' from 'C:\Users\User\Documents\GitHub\tibia-ts3-teamspeakbot'
    at Function.module.exports [as sync] (C:\Users\User\Documents\GitHub\tibia-ts3-teamspeakbot\node_modules\resolve\lib\sync.js:74:15)
    at Object.<anonymous> (C:\Users\User\Documents\GitHub\tibia-ts3-teamspeakbot\node_modules\@babel\node\lib\_babel-node.js:158:32)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

If i drag the dotenv folder to the root directory and change ts3-setup to babel-node -r dotenv/config ./src/scripts/setup in package.json I get the following:

```
× There was some error starting the server
(node:188468) UnhandledPromiseRejectionWarning: Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:27800)
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at internalConnect (net.js:962:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:280:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1115:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
(node:188468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:188468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Ethaan** [comment]
Thats seems an error with the TS host server missing

**Comment by Ethaan** [comment]
@Bielzinero https://github.com/ethkat/tibia-ts3-teamspeakbot/pull/31 fix this, please pull from master
