### ISSUE TITLE
 Error executing command on bot

### ISSUE THREAD

**Issue by alexsandrejr** [ethkat/tibia-ts3-teamspeakbot#27]
When running the command on ts3! addFriend $ {enemyName} the following error appears in the terminal:

TypeError: Cannot read property 'info' of undefined
    at info (/root/tibia-ts3-teamspeakbot/src/api/crone/lists.js:158:41)
    at Array.forEach (<anonymous>)
    at forEach (/root/tibia-ts3-teamspeakbot/src/api/crone/lists.js:158:30)
    at tryCatch (/root/tibia-ts3-teamspeakbot/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/root/tibia-ts3-teamspeakbot/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/root/tibia-ts3-teamspeakbot/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/root/tibia-ts3-teamspeakbot/src/api/crone/lists.js:36:103)
    at _next (/root/tibia-ts3-teamspeakbot/src/api/crone/lists.js:38:194)
    at <anonymous>

**Comment by alexsandrejr** [comment]
And one more thing!
Bot doesn't have the following nickname in teamspeak3:
https://prnt.sc/qh8uq4

**Comment by Ethaan** [comment]
Did you setup the config correctly?

**Comment by alexsandrejr** [comment]
the problem i am having now is that the tibia website rejects my connection.
I also have another problem where the bot when executing the setup creates the rooms automatically but does not give the permissions to the server admin.

**Comment by alexsandrejr** [comment]
do you have any tips to solve these problems?

**Comment by gudwal** [comment]
@Ethaan I believe it would be better to obtain statistics directly from tibiadata.com instead of obtaining them from tibia.com why many blocks are being generated with cloudflare.

**Comment by alexsandrejr** [comment]
excelent idea

**Comment by Ethaan** [comment]
hmm interesting, i didn't know [tibiadata](http://tibiadata.com) exists

**Comment by Ethaan** [comment]
@alexsandrejr wanna help me changing from `tibia-API` to `tibiadata`?

**Comment by Ethaan** [comment]
Lets continue conversation here https://github.com/ethkat/tibia-ts3-teamspeakbot/issues/30
