### ISSUE TITLE
Error: Cannot find module 'node_modules/dotenv/config'

### ISSUE THREAD

**Issue by gudwal** [ethkat/tibia-ts3-teamspeakbot#28]
yarn run v1.21.1
$ babel-node -r node_modules/dotenv/config ./src/scripts/setup
/root/tibia-ts3-teamspeakbot/node_modules/resolve/lib/sync.js:83
    throw err;
    ^

Error: Cannot find module 'node_modules/dotenv/config' from '/root/tibia-ts3-teamspeakbot'
    at Function.resolveSync [as sync] (/root/tibia-ts3-teamspeakbot/node_modules/resolve/lib/sync.js:81:15)
    at Object.<anonymous> (/root/tibia-ts3-teamspeakbot/node_modules/@babel/node/lib/_babel-node.js:166:32)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

-------------------------

[root@DESKTOP-UFJ7E2F tibia-ts3-teamspeakbot]# ls -l node_modules/dotenv/
total 24
-rwxrwxrwx 1 root root 3919 Oct 26  1985 CHANGELOG.md
-rwxrwxrwx 1 root root  189 Oct 26  1985 config.js
drwxrwxrwx 1 root root  512 Feb 26 18:03 lib
-rwxrwxrwx 1 root root 1294 Oct 26  1985 LICENSE
-rwxrwxrwx 1 root root 3858 Feb 26 18:03 package.json
-rwxrwxrwx 1 root root 9542 Oct 26  1985 README.md

**Comment by shayneoneill** [comment]
Did you ever find a solution to this?
