### ISSUE TITLE
!addFriendsByGuild command issue

### ISSUE THREAD

**Issue by gudwal** [ethkat/tibia-ts3-teamspeakbot#30]
After using !addFriendsByGuild  bot is not working.

[root@server tsbot]# yarn ts3-start
yarn run v1.22.4
$ babel-node -r node_modules/dotenv/config ./src/scripts/start
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
✔ Server running!, happy hunting
(node:5691) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-
TypeError: Cannot read property 'info' of undefined
    at info (/tsbot/src/api/crone/lists.js:158:41)
    at Array.forEach (<anonymous>)
    at forEach (/tsbot/src/api/crone/lists.js:158:30)
    at tryCatch (/tsbot/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/tsbot/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/tsbot/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/tsbot/src/api/crone/lists.js:36:103)
    at _next (/tsbot/src/api/crone/lists.js:38:194)
TypeError: Cannot read property 'info' of undefined
    at info (/tsbot/src/api/crone/lists.js:158:41)
    at Array.forEach (<anonymous>)
    at forEach (/tsbot/src/api/crone/lists.js:158:30)
    at tryCatch (/tsbot/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/tsbot/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/tsbot/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/tsbot/src/api/crone/lists.js:36:103)
    at _next (/tsbot/src/api/crone/lists.js:38:194)
TypeError: Cannot read property 'info' of undefined
    at info (/tsbot/src/api/crone/lists.js:158:41)
    at Array.forEach (<anonymous>)
    at forEach (/tsbot/src/api/crone/lists.js:158:30)
    at tryCatch (/tsbot/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/tsbot/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/tsbot/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/tsbot/src/api/crone/lists.js:36:103)
    at _next (/tsbot/src/api/crone/lists.js:38:194)

**Comment by alexsandrejr** [comment]
which vps are you using?

**Comment by gudwal** [comment]
Centos 7

**Comment by alexsandrejr** [comment]
@Ethaan I don't understand programming very well, I'm just an enthusiast.

**Comment by alexsandrejr** [comment]
I would like to help in some way because I really liked the bot's intention, but I don't really understand programming to do that. :(

**Comment by Ethaan** [comment]
@alexsandrejr np, you can help testing, here is the PR with the work with all the fixes and using tibia stats https://github.com/ethkat/tibia-ts3-teamspeakbot/pull/31
