### ISSUE TITLE
I need help with the following error

### ISSUE THREAD

**Issue by vinisilv4** [ethkat/tibia-ts3-teamspeakbot#46]
npm run ts3-setup

> carlin-backend@0.0.1 ts3-setup /home/tibia-ts3-teamspeakbot
> babel-node -r ./node_modules/dotenv/config.js ./src/scripts/setup

/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/files/plugins.js:175
    throw e;
    ^

Error: Cannot resolve module '@babel/preset-env'
    at parseFloat (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/files/plugins.js:97:11)
    at resolveStandardizedName (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/files/plugins.js:100:7)
    at resolvePreset (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/files/plugins.js:48:10)
    at loadPreset (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/files/plugins.js:67:20)
    at createDescriptor (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/home/tibia-ts3-teamspeakbot/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)

npm ERR! Linux 5.3.13-1-pve
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ts3-setup"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! carlin-backend@0.0.1 ts3-setup: `babel-node -r ./node_modules/dotenv/config.js ./src/scripts/setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the carlin-backend@0.0.1 ts3-setup script 'babel-node -r ./node_modules/dotenv/config.js ./src/scripts/setup'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the carlin-backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node -r ./node_modules/dotenv/config.js ./src/scripts/setup
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs carlin-backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls carlin-backend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tibia-ts3-teamspeakbot/npm-debug.log

**Comment by vinisilv4** [comment]
I managed to solve the error above, but I see that masspoke commands take a long time to be performed, how can I fix this?

**Comment by Eduardjo** [comment]
help, how did you solve it?
